version: "3"
services:
  traefik:
    image: traefik:1.5
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"  
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=nuvemtecnologia.com"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  nodejs:
    image: danielprietsch/alpinenodehello
    volumes:
      - /etc/docker/volumes/NodeApp:/data
    networks:
      - traefik
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=3000"
        - "traefik.backend=/"
        - "traefik.frontend.rule=Path:/"
networks:
  webgateway:
    driver: overlay
    external: true
  traefik:
    driver: overlay

